// Generated build artifact, not a second policy implementation. Works in browsers and Node tests.
import { readFileSync, writeFileSync } from 'node:fs';
const binary = readFileSync(new URL('../web/generated/den_core_bg.wasm', import.meta.url));
writeFileSync(new URL('../web/generated/wasm-data.js', import.meta.url),
  `// Generated by scripts/embed-wasm.mjs; do not edit.\nexport default ${JSON.stringify(binary.toString('base64'))};\n`);
